/*
  fablabway.com
  file:        youdir.sql
  project:     oracle directories performances
  description:  oracle
  author:       Mauro Rossolato
  licence:      Creative Commons BY-NC-ND
  when        who   what
  -----------------------------------
  19.05.2018  mr    creates
*/

SET LINESIZE 200
SET SERVEROUTPUT ON SIZE 1000000

DECLARE
    V_FILE      UTL_FILE.FILE_TYPE;
    VTIME NUMBER; 
    VTIME2 NUMBER; 
    WMIADIR VARCHAR2(40);
    WTHISONE VARCHAR2(30) := 'YOUDIR (2019)';
    WMIOPATH VARCHAR2(80);
    WMSGSENTENCE VARCHAR2(100) := 'ROCK ''LL NEVER DIE!';
    WMSGROW VARCHAR2(4000);
    WMSGROWBYTES NUMBER;
    WHOWMANY NUMBER;
    WNUMLOOP NUMBER;
BEGIN
  WHOWMANY := 10;
  WNUMLOOP := 4000;
  WMSGROW := RPAD(WMSGSENTENCE||' ',WHOWMANY*LENGTH(WMSGSENTENCE),WMSGSENTENCE);
  SELECT NVL(VSIZE(WMSGROW)*WNUMLOOP,0) INTO WMSGROWBYTES FROM DUAL;
  DBMS_OUTPUT.PUT_LINE(WTHISONE ||' - https://github.com/fablabway/acheloo');
  DBMS_OUTPUT.PUT_LINE('==> ORACLE DIRE PERFORMANCES');
  DBMS_OUTPUT.PUT_LINE('==> WRITE A FILE '||TO_CHAR(WMSGROWBYTES)||' BYTES LONG');
  DBMS_OUTPUT.PUT_LINE(RPAD('-',50,'-'));
  FOR WDIR IN (SELECT DIRECTORY_NAME,DIRECTORY_PATH FROM ALL_DIRECTORIES ORDER BY DIRECTORY_NAME
)
  LOOP
  BEGIN
    VTIME := DBMS_UTILITY.GET_TIME();
    WMIADIR := WDIR.DIRECTORY_NAME;
    WMIOPATH := WDIR.DIRECTORY_PATH;
    V_FILE := UTL_FILE.FOPEN(WMIADIR, 'TESTMR.TXT', 'W');
    FOR WNDX IN 0..WNUMLOOP-1 LOOP
      UTL_FILE.PUT_LINE (V_FILE, 'LINE '||TO_CHAR(WNDX)||' '||WMSGROW);
    END LOOP;
    UTL_FILE.FFLUSH (V_FILE);
    UTL_FILE.FCLOSE (V_FILE);
    VTIME2 := DBMS_UTILITY.GET_TIME();
    DBMS_OUTPUT.PUT_LINE('WRITING ON '||WMIADIR||' ('||WMIOPATH||') IN '||TO_CHAR(((VTIME2-VTIME)*10))||'(MS)');
    EXCEPTION
   WHEN OTHERS THEN
   DBMS_OUTPUT.PUT_LINE('*** ERROR ON LOOP '||RTRIM(WMIADIR)||'('||WMIOPATH||') - ORA'||SQLCODE);  
    END;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE(RPAD('-',50,'-'));
END;
/

